site: Christoph
url: https://bernerbruno.github.io
title: Bernerbruno
description: I write about Physics and Neuroscience.
twitter:
  username: bernerbruno
  card: summary
  creator: bernerbruno
author:
  twitter: bernerbruno
  name: bernerbruno
  avatar:
  email: christoph.otte@icloud.com
  url: https://phoebe.pubpub.org
permalink: pretty

baseurl: ""

highlighter: rouge

markdown: kramdown
kramdown:
  input: kramdown
  syntax_highlighter: rouge
  math_engine: katex

exclude:
  - .jekyll-cache
  - vendor
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"