site: Christoph
url: https://christoph-otte.github.io
title: Christoph Otte
description: This site collects notes.
twitter:
  username: christoph-otte
  card: summary
  creator: christoph-otte
author:
  twitter: christoph-otte
  name: christoph-otte
  avatar:
  email: christoph.otte@icloud.com
  url: https://phoebe.pubpub.org
permalink: pretty

baseurl: ""

future: true

highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - .jekyll-cache
  - vendor
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  projects:
    output: true
    permalink: /projects/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "post"